version: '3.8'

services:
  clickhouse:

    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_PORT:-8123}:8123" # HTTP port
      - "${CLICKHOUSE_TCP_PORT:-9000}:9000" # Native port
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse-server
      - ./config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml:ro
      - ./clickhouse_backups:/backups
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-default}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  clickhouse_data:
  clickhouse_logs:
  clickhouse_backups:
  grafana_data: